extend-exclude = [".github", "proto", "gen", "alembic", "**/sqlalchemy/__init__.py"]
force-exclude = true
line-length = 88
show-fixes = true
target-version = "py312"

[format]
quote-style = "single"
skip-magic-trailing-comma = false

[lint]
extend-select = [
    "F", "E", "W", "RUF",
    "N", "UP", "ANN", "ASYNC",
    "S", "FBT", "B", "A",
    "COM", "C4", "T10", "EM",
    "ISC", "LOG", "G", "PIE",
    "T20", "PT", "Q", "RSE",
    "RET", "SLF", "SIM", "TID",
    "TCH", "ARG", "PTH", "ERA",
    "PL", "TRY", "PERF"
]
ignore = [
    "PERF101", "ISC001", "ARG001",
    "A005", "N805", "UP037",
    "UP007", "F821", "RUF001"
]

[lint.flake8-quotes]
inline-quotes = 'single'

[lint.flake8-tidy-imports]
ban-relative-imports = 'all'

[lint.mccabe]
max-complexity = 8