extend-exclude = [".github", "proto", "gen", "alembic", "**/sqlalchemy/__init__.py"]
force-exclude = true
line-length = 88
show-fixes = true
target-version = "py312"

[format]
quote-style = "single"
skip-magic-trailing-comma = false

[lint]
extend-select = [
    "F", "E", "W", "RUF",
    "N", "UP", "ANN", "ASYNC",
    "S", "FBT", "B", "A",
    "COM", "C4", "T10", "EM",
    "ISC", "LOG", "G", "PIE",
    "T20", "PT", "Q", "RSE",
    "RET", "SLF", "SIM", "TID",
    "TCH", "ARG", "PTH", "ERA",
    "PL", "TRY", "PERF"
]
ignore = [
    "PERF101", "ISC001", "ARG001",
    "A005", "N805", "UP037",
    "UP007", "F821", "RUF001",
    "PLR0913", "ANN401"
]

[lint.flake8-quotes]
inline-quotes = 'single'

[lint.flake8-tidy-imports]
ban-relative-imports = 'all'

[lint.mccabe]
max-complexity = 8

[lint.extend-per-file-ignores]
"**/tests/**/*.py" = [
    "S101", # asserts allowed in tests...
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
]
