"""empty message

Revision ID: 25169a3985a3
Revises: 99d2294771bf
Create Date: 2025-02-16 17:18:58.017761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '25169a3985a3'
down_revision: Union[str, None] = '99d2294771bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'impressions', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'impressions', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'impressions', type_='foreignkey')
    op.drop_constraint(None, 'impressions', type_='foreignkey')
    # ### end Alembic commands ###
