"""empty message

Revision ID: 2576039db03f
Revises: fd399ebfeb53
Create Date: 2025-02-21 00:50:46.478340

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2576039db03f'
down_revision: Union[str, None] = 'fd399ebfeb53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_advertisers',
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('advertiser_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.PrimaryKeyConstraint('telegram_id', 'advertiser_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_advertisers')
    # ### end Alembic commands ###
