"""empty message

Revision ID: 43b3fe35409a
Revises: 2576039db03f
Create Date: 2025-02-21 22:01:56.776129

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43b3fe35409a'
down_revision: Union[str, None] = '2576039db03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_login_key', 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clients_login_key', 'clients', ['login'])
    # ### end Alembic commands ###
