"""empty message

Revision ID: 783cb5b979eb
Revises: 25169a3985a3
Create Date: 2025-02-16 19:25:04.348355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '783cb5b979eb'
down_revision: Union[str, None] = '25169a3985a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impressions', sa.Column('cost', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('impressions', 'cost')
    # ### end Alembic commands ###
