"""empty message

Revision ID: 99d2294771bf
Revises: 16739ba7bee5
Create Date: 2025-02-16 17:13:09.854341

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '99d2294771bf'
down_revision: Union[str, None] = '16739ba7bee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impressions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'advertisers', ['id'])
    op.create_unique_constraint(None, 'clients', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'advertisers', type_='unique')
    op.drop_table('impressions')
    # ### end Alembic commands ###
