"""empty message

Revision ID: b642ff7c4b90
Revises: 4d2296302b0e
Create Date: 2025-02-14 16:35:58.686641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b642ff7c4b90'
down_revision: Union[str, None] = '4d2296302b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('impressions_limit', sa.Integer(), nullable=False),
    sa.Column('clicks_limit', sa.Integer(), nullable=False),
    sa.Column('cost_per_impression', sa.Float(), nullable=False),
    sa.Column('cost_per_click', sa.Float(), nullable=False),
    sa.Column('ad_title', sa.String(), nullable=False),
    sa.Column('ad_text', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    # ### end Alembic commands ###
